<header role="header"/>
		
		   <nav class="menu" role="navigation"/>
		     <div class="m-right">
			    <h1 class ="logo">AGENCE</h1>
			</div>
			<div class="m-left">
			   <a href="Accueil.html"class="m-link"><i class="fa fa-home" aria-hidden="true"></i> Accueil</a>
			   <a href="vuescontroleurs/formRechercheBien.php"class="m-link"><i class="fa fa-paste" aria-hidden="true"></i> Acheter</a>
			   <a href="Page 3.html"class="m-link"><i class="fa fa-info-circle" aria-hidden="true"></i> Contact</a>
			</div>
	       </nav>
		   
		</header>