<footer>
		 <div class="contenu-footer">
		    <div class="bloc footer-agence">
			  <h3>Nos agence<h3>
			  <ul class="liste-agence">
			    <li><a href="#">Roubaix</a></li>
				<li><a href="#">Montpellier</a></li>
				<li><a href="#">Strasbourg</a></li>
				<li><a href="#">Paris</a></li>
			</ul>
		 </div>
		    <div class="bloc footer-apropos">
			  <h3>A propos<h3>
			   <p>03.69.54.12.09</p>
			   <p>agence.lz@contact.com</p>
			   <p>5 rue De Gaule,Paris VII,75000</p>
			   
		 </div>
			<div class="bloc footer-simulateurs">
			  <h3>Simulateurs<h3>
			  <ul class="liste-simulateurs">
			    <li><a href="#">PRET IMMOBILIER</a></li>
				<li><a href="#">FRAIS DE NOTAIRE</a></li>
				<li><a href="#">TABLEAU D'AMORTISSEMENT</a></li>
			</ul>
		 </div>
		    
		
		</div>
		</footer>